### ISSUE TITLE
test 

### ISSUE THREAD

**Issue by Chiroyce1** [Chiroyce1/Chiroyce1#12]

**Comment by iamperry294** [comment]
> @iamperry294 let me know who it is over here

Wouldn't it be better for me to just use [Contact Us](https://scratch.mit.edu/contact-us/)?

**Comment by Chiroyce1** [comment]
> Wouldn't it be better for me to just use [Contact Us](https://scratch.mit.edu/contact-us/)?

Do that, and also let me know.

**Comment by Chiroyce1** [comment]
Well there is no harm in letting me know...

**Comment by Chiroyce1** [comment]
@iamperry294 ^^^

**Comment by iamperry294** [comment]
@Chiroyce1 I can't here. Perhaps on MC?

**Comment by Chiroyce1** [comment]
@iamperry294 we already talked about this LOL - btw i forgot the username and name of the MC repl

**Comment by Chiroyce1** [comment]
yeah right... 
<img width="349" alt="image" src="https://user-images.githubusercontent.com/97374054/171993766-d2214267-1f61-44eb-9b0e-73acf4be278c.png">

**Comment by Chiroyce1** [comment]
i was able to signup, but the messaging system is broken
<img width="352" alt="image" src="https://user-images.githubusercontent.com/97374054/171993799-907dc8d7-3925-47ac-b199-d46b3e2729cd.png">
